### PR TITLE
Refactoring the debugging output.

### PR DESCRIPTION
**Pull request by vel21ripn**
levels of debug output:
 0 - ERROR: Only for errors.
 1 - TRACE: Start of each packets and if found protocol.
 2 - DEBUG: Start of searching each protocol and excluding protocols.
 3 - DEBUG_EXTRA: For all other messages.

Added field ndpi_struct->debug_logging for enable debug output of each protocols.

Simple macros for debugging output are added:
NDPI_LOG_ERR(), NDPI_LOG_INFO(), NDPI_LOG_DBG(), NDPI_LOG_DBG2(),
NDPI_EXCLUDE_PROTO()

### CODE REVIEW

**Comment by vel21ripn** [comment]
\_\_KERNEL\_\_ and double underscore removed.
Are there any other questions or suggestions?

**Comment by kYroL01** [comment]
GREAT! I think for this pull request is enough. Thank you!

**Comment by kYroL01** [comment]
Hi @vel21ripn I see many 
`warning of implicit declaration of function ‘NDPI_LOG_INFO’`
` warning: implicit declaration of function ‘NDPI_LOG_DBG’`
`warning: implicit declaration of function ‘NDPI_EXCLUDE_PROTO’`

Maybe you miss to include ndpi_define.h in protocol dissectors. Can u check please ?

**Comment by vel21ripn** [comment]
Did you run autogen.sh? Unfortunately the file ndpi_define.h is generated from ndpi_define.h.in.

**Comment by vel21ripn** [comment]
Are there any other reasons that prevent the approval of my PR?

**Comment by kYroL01** [comment]
@vel21ripn sorry for delay.It's correct after autogen.sh

Thank you!

**Pull request merged**
