### PR TITLE
Remove Google+ support

### PR DESCRIPTION
**Pull request by 0xA50C1A1**
Please sign (check) the below before submitting the Pull Request:

- [x] I have signed the ntop Contributor License Agreement at https://github.com/ntop/legal/blob/main/individual-contributor-licence-agreement.md
- [x] I have read the contributing guide lines at https://github.com/ntop/nDPI/blob/dev/CONTRIBUTING.md
- [x] I have updated the documentation (in doc/) to reflect the changes made (if applicable)

Describe changes:

Google+ was discontinued in 2019, so I think that its protocol id can be freed for reuse.

### CODE REVIEW

**Comment by IvanNardi** [comment]
Could you fill in the CLA, please?

**Comment by 0xA50C1A1** [comment]
> Could you fill in the CLA, please?

Done.

**Review by IvanNardi — APPROVED** [review]
It makes sense

**Comment by IvanNardi** [comment]
Thanks

**Pull request merged**
