### PR TITLE
ndpireader: add json output back.

### PR DESCRIPTION
**Pull request by vitalivanov**
- partial revert of:
    commit 51cfdfb0d80a7bbcc11bc3b95d1696d8dae900c2
    Author: Luca Deri <deri@ntop.org>
    Date: Sun Nov 17 17:51:45 2019 +0100
      Removed unused JSON-C code

- Json option is changed from 'j' to 'k' as it's used in the new codebase.
- use HAVE_LIBJSON_C instead of HAVE_JSON_C.
- tabs vs spaces clean ups.

Signed-off-by: Vitaliy Ivanov <vitaliyi@interfacemasters.com>

 Conflicts:
	example/ndpiReader.c

### CODE REVIEW

**Comment by lucaderi** [comment]
Thanks you

**Comment by IvanNardi** [comment]
This patch broke the `ndpiReader` output when "-v2" option is used.
That means that unit tests are now completely broken.
There are also some (trivial) compilation errors that need to be fixed.
@vitalivanov , could you take a look, please?

**Comment by lucaderi** [comment]
I am also looking at it as I have realized it too

**Comment by lucaderi** [comment]
@vitalivanov I have fixed the dev branch, please send a PR for the stable branch

**Comment by vitalivanov** [comment]
> please send a PR for the stable branch
ok i will

@lucaderi 
@IvanNardi 

a.
4 for Potentially overflowing call to snprintf
1 for Local variable hides global variable

these are part of old npireader json patch...

b.
tabs vs spaces - yes, agree, but reading that was a pain...

c. v2 - if luca addressed this in dev - I would update to 4.2-stable.
it still works with v4:)

**Pull request merged**
