### PR TITLE
Refactor ndpi_strnstr to use ndpi_memmem

### PR DESCRIPTION
**Pull request by 0xA50C1A1**
Please sign (check) the below before submitting the Pull Request:

- [x] I have signed the ntop Contributor License Agreement at https://github.com/ntop/legal/blob/main/individual-contributor-licence-agreement.md
- [x] I have read the contributing guide lines at https://github.com/ntop/nDPI/blob/dev/CONTRIBUTING.md
- [x] I have updated the documentation (in doc/) to reflect the changes made (if applicable)

Link to the related [issue](https://github.com/ntop/nDPI/issues):

Describe changes:

### CODE REVIEW

**Comment by IvanNardi** [comment]
That's exactly what I was thinking (t's a pleasure to hear from you again!)

**Comment by IvanNardi** [comment]
@pasabanov, any thoughts?

**Comment by pasabanov** [comment]
> @pasabanov, any thoughts?

Yes, I have a few thoughts.

1. Using `ndpi_memmem` in `ndpi_strnstr` slightly slows down the execution of `ndpi_strnstr` when `needle_len == 1`.  
It might be worth returning this optimization to `ndpi_strnstr`.
3. There is also the possibility to getting rid of the checks in `ndpi_strnstr` altogether, as they are already performed in `ndpi_memmem`. I can see the potential to write `ndpi_strnstr` as a one-liner.

Additionally, I have a thought about `ndpi_memmem`:
It might make sense to check `current < end_of_search` or, similarly, `needle_len <= haystack_len` only once, and then use an infinite loop instead of `while (current < end_of_search)`, because `memchr` on each iteration returns either `NULL` or a pointer between `current` and `end_of_search`.

And one more question: can you provide a link to your code style guide? I assume that you prefer the style without line breaks before curly braces.

**Comment by 0xA50C1A1** [comment]
>     2. There is also the possibility to getting rid of the checks in `ndpi_strnstr` altogether, as they are already performed in `ndpi_memmem`. I can see the potential to write `ndpi_strnstr` as a one-liner.

You mean the typical `NULL` checks? I guess I can remove them, since they are already present in `strlen` and `strnlen`, as well as in `ndpi_memmem`.

**Comment by pasabanov** [comment]
> It might make sense to check `current < end_of_search` or, similarly, `needle_len <= haystack_len` only once

Actually, the check `needle_len <= haystack_len` in `ndpi_memmem` occurs in `if (!haystack || !needle || haystack_len < needle_len)`, so I think we can just replace `while (current < end_of_search)` with `while (1)` or another variant of an infinite loop.

**Comment by 0xA50C1A1** [comment]
> > It might make sense to check `current < end_of_search` or, similarly, `needle_len <= haystack_len` only once
> 
> Actually, the check `needle_len <= haystack_len` in `ndpi_memmem` occurs in `if (!haystack || !needle || haystack_len < needle_len)`, so I think we can just replace `while (current < end_of_search)` with `while (1)` or another variant of an infinite loop.

Thanks, that's a good idea, might increase performance a bit. I'll modify it now.

**Comment by pasabanov** [comment]
> You mean the typical `NULL` checks? I guess I can remove them, since they are already present in `strlen` and `strnlen`, as well as in `ndpi_memmem`.

I mean all the checks: `if (!haystack || !needle)`, `if (needle_len == 0)` and `if (needle_len > hs_real_len)`. They're all performed in `ndpi_memmem`.

Oh, wait! I think that `strlen` and `strnlen` do not check for `NULL`, so you should keep the `if (!haystack || !needle)` check.

**Comment by 0xA50C1A1** [comment]
> Oh, wait! I think that `strlen` and `strnlen` do not check for `NULL`, so you should keep the `if (!haystack || !needle)` check.

Maybe it depends on the implementation, glibc has these checks. Alright, I'll keep them.

**Comment by pasabanov** [comment]
I think it would be prettier to write `return (char *)ndpi_memmem(haystack, strnlen(haystack, len), needle, strlen(needle));`.

**Comment by 0xA50C1A1** [comment]
> I think it would be prettier to write `return (char *)ndpi_memmem(haystack, strnlen(haystack, len), needle, strlen(needle));`.

Alright, let's make this simpler.

**Review by IvanNardi — APPROVED** [review]

**Comment by IvanNardi** [comment]
Thanks everyone

**Pull request merged**
