### PR TITLE
Fixed Mingw64 build, SonerCloud-CI and more.

### PR DESCRIPTION
**Pull request by utoni**

### CODE REVIEW

**Comment by lucaderi** [comment]
@lnslbrty Why do we need all windows/WpdPack/ files?

**Comment by utoni** [comment]
> @lnslbrty Why do we need all windows/WpdPack/ files?

Probably not all files are required. For now I dunno which ones are superfluous besides Packet.lib
But for a succesful Mingw compilation, at least some header files and the import library wpcap.lib are required.

**Comment by utoni** [comment]
I tried to remove as much as possible from `windows/WpdPack`. I've also removed the broken VisualStudio integration. Some serious issues, mostly path related. If there is a need for VS integration, I might be able to fix that (requires some time).

I did not test any configure/make with Darwin or *BSD.

**Comment by lucaderi** [comment]
It works on Darwin, thank you.

**Pull request merged**
