### PR TITLE
Remove some useless fuzzing target

### PR DESCRIPTION
**Pull request by IvanNardi**
We don't need specific targets to reproduce fuzzing issues. After all, calling `./fuzz/fuzz_process_packet_with_main $ARTIFACT_FILE` is equivalento to `./fuzz/fuzz_process_packet $ARTIFACT_FILE`

### CODE REVIEW

**Comment by IvanNardi** [comment]
If I am reading the GIT history correctly, this kind of targets has been introduced the first time in  4a6c525d.
@utoni, am I missing something?

**Comment by utoni** [comment]
I was using this mechanism to reproduce memory errors with gdb and binary files generated by the fuzzer. Is there any other/better way to do this?

**Comment by IvanNardi** [comment]
> I was using this mechanism to reproduce memory errors with gdb and binary files generated by the fuzzer. Is there any other/better way to do this?

You can use the "standard" fuzzer executable (i.e. without "main") in the same way.
Example (with  `~/Downloads/timeout-00c89476a9a3fb4cd23fc2ebef444ac8dea862d1` being a binary file generated by previous fuzzing that triggers an error)
```
ivan@ivan-Latitude-E6540:~/svnrepos/nDPI(lto-gold)$ ./fuzz/fuzz_process_packet ~/Downloads/timeout-00c89476a9a3fb4cd23fc2ebef444ac8dea862d1                                       <---- Note fuzz_process_packet NOT fuzz_process_packet_with_main
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 3823404294
./fuzz/fuzz_process_packet: Running 1 inputs 1 time(s) each.
Running: /home/ivan/Downloads/timeout-00c89476a9a3fb4cd23fc2ebef444ac8dea862d1
Executed /home/ivan/Downloads/timeout-00c89476a9a3fb4cd23fc2ebef444ac8dea862d1 in 34 ms
***
*** NOTE: fuzzing was not performed, you have only
***       executed the target code on a fixed set of inputs.
***
ivan@ivan-Latitude-E6540:~/svnrepos/nDPI(lto-gold)$ gdb ./fuzz/fuzz_process_packet
GNU gdb (Ubuntu 10.2-0ubuntu1~20.04~1) 10.2
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./fuzz/fuzz_process_packet...
(No debugging symbols found in ./fuzz/fuzz_process_packet)
(gdb) 
(gdb) run ~/Downloads/timeout-00c89476a9a3fb4cd23fc2ebef444ac8dea862d1
Starting program: /home/ivan/svnrepos/nDPI/fuzz/fuzz_process_packet ~/Downloads/timeout-00c89476a9a3fb4cd23fc2ebef444ac8dea862d1
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1830238792
[New Thread 0x7ffff62d5700 (LWP 109703)]
/home/ivan/svnrepos/nDPI/fuzz/fuzz_process_packet: Running 1 inputs 1 time(s) each.
Running: /home/ivan/Downloads/timeout-00c89476a9a3fb4cd23fc2ebef444ac8dea862d1
Executed /home/ivan/Downloads/timeout-00c89476a9a3fb4cd23fc2ebef444ac8dea862d1 in 32 ms
***
*** NOTE: fuzzing was not performed, you have only
***       executed the target code on a fixed set of inputs.
***
[Thread 0x7ffff62d5700 (LWP 109703) exited]
[Inferior 1 (process 109699) exited normally]
(gdb) 

```
From: https://llvm.org/docs/LibFuzzer.html

```
If a list of files (rather than directories) are passed to the fuzzer program, then it will re-run those files as test inputs but will not perform any fuzzing. In this mode the fuzzer binary can be used as a regression test (e.g. on a continuous integration system) to check the target function and saved inputs still work.
```

**Review by utoni — APPROVED** [review]
Thanks. I did not know that.

**Pull request merged**
