### PR TITLE
Dns extended 

### PR DESCRIPTION
**Pull request by ragostino**
the dns dissector has been extended to parse many query/response messages (zone transfer on tcp included)
add tcp fragmentation managing and realignments (prevalently for dns packets)
added a dns-zone-transfer pcap file to test

### CODE REVIEW

**Comment by lucaderi** [comment]
Sorry for the delay. I have tested the code and found some problems
- There are plenty of tracings that need to be removed and eventually turned into a security risk
ERR(checkDnsNameAndAllocate): error retrieving dns name [qsName]
ERR(parseDnsQSecs): dns name retrieving error: QS NAME 
ERR(parseDnsQSecs): missing 1 DNS QS parsing the section!
 ERR [protocols/dns.c:search_valid_dns:1717]: 	ID=#FDC6h, malformed/risky? queries expected:1, current offset:12 vs packet len:44
 ERR [protocols/dns.c:search_valid_dns:1755]: 	ID=#1AC8h, R malformed/risky? queries_num:1, hflag:00h, answer_num:89, auth_num:43690, add_num:43690; current offset:12 vs packet len:40 
 ERR [protocols/dns.c:search_valid_dns:1755]: 	ID=#3FC8h, R malformed/risky? queries_num:43690, hflag:1aah, answer_num:43690, auth_num:43690, add_num:43690; current offset:12 vs packet len:44 
 ERR [protocols/dns.c:search_valid_dns:1755]: 	ID=#1ACAh, R malformed/risky? queries_num:1, hflag:00h, answer_num:170, auth_num:43690, add_num:43690; current offset:12 vs packet len:40 
E

- malformed DNS packets detection (e.g. see fuzz-2006-06-26-2594.pcap or malformed_dns.pcap in tests) are no longer detected as malformed

Please address these small issues so we can marge the code. Thank you

**Comment by ragostino** [comment]
Translated  reply ===============================================
Good morning.
I had put my thumb up as a confirmation of the report.
This is just to inform you of the intention to contact you as soon as possible.
Unfortunately, I'm a bit busy at the moment and I'm not sure when.

Yours truly.
Roberto AGOSTINO


On Wed 2 Dec 2020 at 14:30 Luca Deri <notifications@github.com>
he wrote:
==========================================================

Buongiorno.
Avevo messo il pollice in su a mo' di riscontro dell'avvenuta segnalazione.
La presente solo per informare dell'intenzione di metterci mano appena
possibile.
Purtroppo al momento sono un po' impegnato e non so bene quando.

Cordialmente.
Roberto AGOSTINO


Il giorno mer 2 dic 2020 alle ore 14:30 Luca Deri <notifications@github.com>
ha scritto:

**Comment by lucaderi** [comment]
I wanted to merge this code but in its current status it is not possible. It introduces too many changes in one shot: fragmentation and DNS for instance, that need to be kept separate IMHO to ease merging. Furthermore it is not clear to me what is the purpose of this work. nDPI is designed to identify protocols and extract limited metadata: what you are proposing in essence is a plugin for DNS if I have understood correctly that can dissect long conversations., thing that I believe it is outside of the scope of nDPI.

**Comment by ragostino** [comment]
Good morning.
> _I wanted to merge this code but in its current status it is not possible. It introduces too many changes in one shot: fragmentation and DNS for instance, that need to be kept separate IMHO to ease merging._ 

Yes it can be done.  I'll have to work a little bit to separate the changes.

> _Furthermore it is not clear to me what is the purpose of this work. nDPI is designed to identify protocols and extract limited metadata: what you are proposing in essence is a plugin for DNS if I have understood correctly that can dissect long conversations., thing that I believe it is outside of the scope of nDPI._

The application in which I have integrated the nDPI library takes care of examining .pcap files, and extracting some important information from the packets for the purposes for which it was made: then, yes, it goes into the deep analysis and follows the conversation; it is not limited to their alone classification.

During my development/library-integration, in addition to extending and detailing the information extracted from the packets, relating to the interested protocols (dns, http and tls), I still had to make changes and corrections that the nDPI library will certainly benefit from.

Although the development related to the dns protocol already allows to increase the ability to detect anomalies in the captured packets, unfortunately without also intervening in the management of segment fragmentation and its possible reordering, some cases will be left out (for instance, the .pcap file added to the project: _dns_zone_transfer.pcap_ contains the request fragmented between packet 4 and 6, and that should not be detected without the fragmentation management).

However, I am in favor of proceeding step by step in integrating the changes.

Indeed, if nothing stands in the way, I would say that we could divide them into the following groupings:
- fragmentation management (impacts everywhere in the library)
- dns dissector (deepens and extends the information retrieved and the checks carried out in the protocol)
- various modifications / improvements that cannot be better classified

I will proceed with this activity, compatibly with the time available.

Best regards.
R.

**Comment by lucaderi** [comment]
Thank you please resubmit individual PRs as soon as you have time to contribute

**Pull request closed without merging**
