### PR TITLE
Added TUYA LAN Protocol dissector.

### PR DESCRIPTION
**Pull request by dsokoloski**
Tuya IoTOS Embedded Wi-Fi and BLE SDK for bk7231n.

Used by many "smart" devices such as LED light strips, bulbs, etc.
https://github.com/tuya/tuya-iotos-embeded-sdk-wifi-ble-bk7231n

Signed-off-by: Darryl Sokoloski <darryl@sokoloski.ca>

### CODE REVIEW

**Comment by IvanNardi** [comment]
@dsokoloski , could you please:
* update unit tests results (`./tests/do.sh` and update files under `tests/results`)
* add `tuya_lp.c` in the two lists in `windows/nDPI.vcxproj` and `windows/nDPI.vcxproj.filters` to fix Windows build

**Review by IvanNardi — APPROVED** [review]
I'll take care of the remaining failure in the unit test

**Comment by IvanNardi** [comment]
Thanks!

**Comment by dsokoloski** [comment]
Thanks Ivan, sorry for the hassle.  Didn't know what action(s) to take there.

**Comment by IvanNardi** [comment]
As a general rule, to fully update the UT results, you need to compile with `--with-pcre` flag and to have nBPF support, but this information is missing in the documentation...
Time to update `README.md`...

**Comment by dsokoloski** [comment]
Good to know, thanks for the info.  I will remember for next time.

**Pull request merged**
