### PR TITLE
Add icmp and icmp6 to calculate splt and bd values.

### PR DESCRIPTION
**Pull request by rkerur**
Signed-off-by: Ravi Kerur <ravi.kerur@viasat.com>

### CODE REVIEW

**Comment by lucaderi** [comment]
Please update this pull request

**Comment by lucaderi** [comment]
Can you please update this contribution with the current source tree?

**Comment by rkerur** [comment]
Can you please check now? I see following in ndpi_icmp

commit 19dbcaa3a9653f1e910db332572dd86ba3963b46
Author: Luca Deri <deri@ntop.org>
Date:   Mon Sep 23 18:04:55 2019 +0200

    Fixes #777

**Comment by lucaderi** [comment]
Thank you

**Pull request merged**
