### PR TITLE
Fix/openbsd build

### PR DESCRIPTION
**Pull request by utoni**

### CODE REVIEW

**Comment by lucaderi** [comment]
@lnslbrty Do we still need to merge this PR or https://github.com/ntop/nDPI/pull/977 is enough?

**Comment by utoni** [comment]
PR #977 should do the job. But I did not verify that.

**Comment by lucaderi** [comment]
Ok so let's close this PR for the time being. Thanks

**Comment by utoni** [comment]
Oh wait. #977 was broken, wasn't it?

**Pull request closed without merging**
