### PR TITLE
Fix byte packing on Windows

### PR DESCRIPTION
**Pull request by sologub**
Added a few #ifdefs to fix byte packing for file btlib.h on Windows/Visual Studio

### CODE REVIEW

**Comment by alagoutte** [comment]
Do you have step/command to build with Windows(Visual Studio ?)

**Comment by sologub** [comment]
I have a Visual Studio project file that makes it compilable, but it is full of hacks and I'm not sure it is worth adding it to this repository.

**Comment by alagoutte** [comment]
It is possible to share the project file ?

**Comment by kYroL01** [comment]
I think is better keep the things simple and clear. For me the patch is correct and mergeable.

**Comment by sologub** [comment]
I agree, thanks!

**Comment by alagoutte** [comment]
@kYroL01 Yes, it will be a separate PR (or a branch on @sologub repo)

**Comment by kYroL01** [comment]
@alagoutte do u need the project file just for test ?

**Comment by kYroL01** [comment]
I don't know if @sologub could share here his project file. So IMHO is better to share privately to you @alagoutte and you can test. If it's ok for both. Now I'm on Linux and I cannot test

**Comment by sologub** [comment]
Yes, please merge this PR as is.

**Comment by alagoutte** [comment]
@kYroL01 Yes, it will be a separate PR (or a branch on @sologub repo)

**Comment by alagoutte** [comment]
@sologub can you send me your projet file for windows ?

**Comment by sologub** [comment]
There is nothing exceptional in there, but still here you are (remove the .txt extention):
[nDPI.vcxproj.txt](https://github.com/ntop/nDPI/files/641427/nDPI.vcxproj.txt)

**Pull request merged**
