### PR TITLE
Refactoring nDPI

### PR DESCRIPTION
**Pull request by kYroL01**
nDPI changes:
- unique ndpi_typedef.h for the typedef used;
- deleted kernel support
- deleted useless defines

### CODE REVIEW

**Comment by vel21ripn** [comment]
Removing kernel mode support is bad idea!
ndpi-netfilter is working.

**Comment by lucaderi** [comment]
I understand your concern but in https://github.com/ntop/nDPI/issues/22 we asked many times to send us a merge request for the net filter code. This didn't happen so we prefer to keep the code tidy and clean. However if you want to share the netfilter code with us, we can accept your contribution.

**Comment by vel21ripn** [comment]
I have branch ndpi-netfilter https://github.com/vel21ripn/nDPI/tree/netfilter (based on 1.7-stable).
Please look at it and express the opinion about the possibility of including it in the main project.
I made a lot of changes.
In July and early August, I was on vacation and could not respond to the request #22

**Comment by lucaderi** [comment]
Please update with respect to our current tree, and send me a diff so we can check this work

**Comment by vel21ripn** [comment]
OK, the difference between the 1.7-stable branches and the current is not very big. I'll try to do it in two days.  Please read the README in the directory ndpi-netfilter my branch.

**Pull request merged**
