### PR TITLE
Revert the revert of 2155dd9 after fixing ntopng Travis

### PR DESCRIPTION
**Pull request by hvanderheide**

### CODE REVIEW

**Comment by kYroL01** [comment]
Cannot accept this pull request due to errors on travis. Could u please check ?

**Comment by hvanderheide** [comment]
The build on OS X failed but I don't think it was something with the code. I merged the latest upstream/dev and everything seems fine

**Comment by kYroL01** [comment]
@simonemainardi could you please check this pull request from the ntopng side ? Last time you find problems with that. Thanks

**Comment by spinenkoia** [comment]
Hi. I also have this problem. I applied this patch to version 2.2, now all is well.

**Comment by lucaderi** [comment]
Thank you

**Pull request merged**
