### PR TITLE
Mullvad VPN service added (based on entry node IP addresses)

### PR DESCRIPTION
**Pull request by snicket2100**

### CODE REVIEW

**Review by IvanNardi — COMMENTED** [review]
Great and complete work.
Just a minor issue: could you add a simple pcap with mulvad traffic? One TLS or DNS flow matching "mullvad.net" domain and one flow matching one of the ips; just a few pkts for each flow...

**Comment by snicket2100** [comment]
Ah yes, of course. I will add.

**Comment by snicket2100** [comment]
Still need to rebase it.

**Review by IvanNardi — APPROVED** [review]

**Comment by IvanNardi** [comment]
Thanks!

**Pull request merged**
