### PR TITLE
Removing unused fields from the id_struct structure.

### PR DESCRIPTION
**Pull request by vel21ripn**
Reduced by 40 bytes.

### CODE REVIEW

**Comment by utoni** [comment]
Can you check if Python && Lua files needs also some adjustment? (I forget that every time.)

**Comment by vel21ripn** [comment]
> Can you check if Python && Lua files needs also some adjustment? (I forget that every time.)

OMG!  python/ndpi.py contains a copy of the structures! 
I added a fix for python.
Can't you automate this somehow? Structures can be retrieved using the "pahole" utility.

The command 'grep -sIR id_struct wireshark' have no result. I don't know how to check this.

**Comment by IvanNardi** [comment]
> I added a fix for python.

Could you update python/ndpi_typestruct.py, too, please?

**Comment by utoni** [comment]
> OMG! python/ndpi.py contains a copy of the structures!
> I added a fix for python.
> Can't you automate this somehow? Structures can be retrieved using the "pahole" utility.

I am planning to do at least a CI check when I am back at home.
But nobody will stop you providing a fix for that. PR's are welcome.

**Comment by vel21ripn** [comment]
> Could you update python/ndpi_typestruct.py, too, please?

Fixed python/ndpi_typestruct.py

There is inconsistency in other structures.
"struct _ndpi_automa {}" has no ac_automa_finalized field.
"struct ndpi_call_function_struct {}" has a different field order and size.

Manually check the files - it is unreliable. We need to generate these files.
It is not difficult to automate the creation of ndpi.py.
The creation of ndpi_typestruct.py will be more complex.

**Comment by IvanNardi** [comment]
@vel21ripn: do you think this PR can be merged "as-is" (deferring any  potential work on python to a follow-up)?

**Comment by aouinizied** [comment]
Yes. Will update cffi bindings once this PR is merged. 
We have definitions in sync here https://github.com/nfstream/nfstream/blob/master/nfstream/engine/engine.py so I will update the one in nDPI repo.
You can open an issue and assign me to have a follow up on this.

**Comment by vel21ripn** [comment]
I made changes to the code for python.
I think this PR can be taken "as-is".
Bugs python code you need to fix a separate PR.

**Comment by IvanNardi** [comment]
Thank you, @vel21ripn

**Pull request merged**
