### PR TITLE
Add Apache Thrift protocol dissector.

### PR DESCRIPTION
**Pull request by utoni**

### CODE REVIEW

**Comment by utoni** [comment]
Missing: ndpiReader method/type printing, pcap file/data with manipulated packets to trigger additional code paths

**Comment by IvanNardi** [comment]
> Missing: ndpiReader method/type printing, pcap file/data with manipulated packets to trigger additional code paths

I particularly dislike not having a pcap triggering the HTTP code path... [I know where this PR came from, so thank you anyway to finish the work...]

**Review by IvanNardi — COMMENTED** [review]
Could you add an entry in `doc/protocols.rst` please?

**Review by IvanNardi — APPROVED** [review]
Thank you

**Pull request merged**
