### PR TITLE
printing a summary of the JA3 fprints for each host

### PR DESCRIPTION
**Pull request by glpaparelli**
The `printResults` function is extended to print a summary of the JA3 fingerprints for each host.  

With `verbose == 1` for each host the `printResults` now print the number of (different) fingerprints (both JA3C and JA3S).

With `verbose == 2` for each host we print the fingerprints (both JA3C and JA3S), in particular for the JA3S it is also printed the server name (if available) and the security status of the cipher used to compute the fingerprint.

### CODE REVIEW

**Comment by lucaderi** [comment]
Please implement
1. Human readable fingerprints as for instance "Protocol statistics" below
2. I need to see all JA3 fingerprints divided *both* by host and fingerprint
3. For each JA3S fingerprint I need to see the server domain name (SNI)

Please implement all this and resubmit

Protocol statistics:
	Safe                        100110 bytes
	Acceptable                   26176 bytes
	Fun                        3170306 bytes
	Unrated                     217226 bytes

host IP 192.168.1.20 has 4 JA3C fingerprints
host IP 52.28.252.195 has 1 JA3S fingerprints
host IP 52.202.64.239 has 1 JA3S fingerprints

**Comment by glpaparelli** [comment]
Implemented all the required features. 

1. the ja3 now is aggregated by host AND the host is aggregated by ja3 fingerprints
2. with ja3s fingerprints it is printed the security status and the server name (if available)
3. now the results are printed in a humanreadble form, as similar as possible to the printing style of 
    the whole program

**Comment by lucaderi** [comment]
Better but formatting is not yet good and similar to the one used until now

Please
1. Remove
"Number of flow with JA3 fingerprint for each host: "
when there is no SSL traffic with JA3 fingerprints

2. In the report
Number of flow with JA3 fingerprint for each host: 
	0	 IP a.b.c.d   	 2 JA3S 
a) number start from 1 as in the list of flows
b) the JA3S identifies a domain If you have multiple fingerprints

if I use -v 2 you have a totally different layout with --- that are out of standard. 
a) remove --- and use an indentation similar to the one used in ndpiReader
b) if a host has multiple fingerprints, avoid duplicating the host IP
c) "JA3C and JA3S for each host, with server name and the cipher security status: " too long: you need to shorten it and indent it

JA3C and JA3S for each host, with server name and the cipher security status: 
-------------------------------------------------------------------------------------------------------------
	1	 5.55.171.181     	 JA3S bf8c087a5081f838efcf2793c6131fdb  (INSECURE) admin.ntop.org
	2	 5.55.171.181     	 JA3S d8b9453ef764bf66b5865ee23dbad717  (INSECURE) admin.ntop.org
-------------------------------------------------------------------------------------------------------------
	3	 5.55.171.156     	 JA3S 455193f33c615ee34c088bbf7b46994f  (INSECURE) 
	4	 5.55.171.156     	 JA3S d8b9453ef764bf66b5865ee23dbad717  (INSECURE) 
-------------------------------------------------------------------------------------------------------------
	5	 192.168.12.131     	 JA3C 2aef69b4ba1938c3a400de4188743185 
-------------------------------------------------------------------------------------------------------------
	6	 2.14.213.100     	 JA3S 292e80b3da40f5cf8c2aac92bf50b17f  (INSECURE) *.ntop.com
-------------------------------------------------------------------------------------------------------------

For each JA3 fingerprint the associated host:
-------------------------------------------------------------------------------------------------------------
	1	 JA3C 2aef69b4ba1938c3a400de4188743185	 IP 192.168.12.131 
-------------------------------------------------------------------------------------------------------------
	2	 JA3S bf8c087a5081f838efcf2793c6131fdb	 IP 65.55.171.181 	admin.ntop.org  (INSECURE)
-------------------------------------------------------------------------------------------------------------
	3	 JA3S 455193f33c615ee34c088bbf7b46994f	 IP 65.55.171.156 	  (INSECURE)
-------------------------------------------------------------------------------------------------------------
	4	 JA3S d8b9453ef764bf66b5865ee23dbad717	 IP 65.55.171.156 	  (INSECURE)
	5	 JA3S d8b9453ef764bf66b5865ee23dbad717	 IP 65.55.171.181 	  (INSECURE)
-------------------------------------------------------------------------------------------------------------
	6	 JA3S 292e80b3da40f5cf8c2aac92bf50b17f	 IP 72.14.213.100 	*.ntop.com  (INSECURE)
-------------------------------------------------------------------------------------------------------------

**Comment by lucaderi** [comment]
@glpaparelli Any news on this matter?

**Comment by glpaparelli** [comment]
> @glpaparelli Any news on this matter

I've been super busy with the Computer Networks course, I am going to commit tomorrow night.

**Comment by glpaparelli** [comment]
@lucaderi 

Now the duplicated IP (same goes with JA3) are not printed (it is printed just one time and the following istances of the same IP (or fingerprint) are left empty. 

Corrected the wrong counter and fixed the printing style, expecially in -v 2 mode

**Pull request closed without merging**
