### PR TITLE
Fix test suite

### PR DESCRIPTION
**Pull request by alagoutte**
May be need to have .travis for check ? ;)

### CODE REVIEW

**Comment by lucaderi** [comment]
@alagoutte I have merged this code even though I am not sure 100% is correct as the IPv6 formatting is different on some platforms and thus the diff (used by tests) won't work. If you want to use a travis fix, please go ahead. Please let me know if you want me to add to the nDPI developers group.

**Comment by alagoutte** [comment]
I have forget to enable .travis for my nDPI repo

**Comment by Mile-Lile** [comment]
capture

it is different formatting on Linux and MS platforms...

**Comment by kYroL01** [comment]
Yes @Mile-Lile , you're right. @lucaderi this is why we have that different output for tests. We have to find a solution, IMHO.
Maybe this can help: https://tools.ietf.org/html/rfc5952#section-2
Looking at some rules, I think we can might catch the IPv6 and create an own function to convert it in a unique standard format for nDPI. What do u think ?

**Comment by alagoutte** [comment]
@kYroL01 sed the output of test suite ?

**Comment by kYroL01** [comment]
@alagoutte sorry, I don't understand what do u mean.

**Comment by alagoutte** [comment]
use sed command (on another tools) for replace :0: by :: for example ?

**Comment by kYroL01** [comment]
Yes, is a possible solution.

**Comment by alagoutte** [comment]
May be open a issue for follow this problem ? (it is possible to create directly a issue from PR ?)

**Pull request merged**
