### PR TITLE
Improved QUIC IETF 0-RTT detection.

### PR DESCRIPTION
**Pull request by utoni**
Signed-off-by: lns <matzeton@googlemail.com>

### CODE REVIEW

**Comment by IvanNardi** [comment]
@utoni , if it is ok with you, I would like to carefully review this change. It may take some days, because it is holiday time in Italy...

BTW, the session you attached is from real traffic?

**Comment by IvanNardi** [comment]
Can I share the session in some (semi) public forums? I would like to ask some questions about this trace

**Comment by utoni** [comment]
> @utoni , if it is ok with you, I would like to carefully review this change. It may take some days, because it is holiday time in Italy...

Take all the time you need. Enjoy your work-free time.

> BTW, the session you attached is from real traffic?

Yes.

**Comment by utoni** [comment]
> Can I share the session in some (semi) public forums? I would like to ask some questions about this trace

Yea, it is already public.

**Comment by IvanNardi** [comment]
I proposed another solution to this issue in #1713. The main advantage is that it correctly decode the Initial/CH received after the 0-RTT, allowing sub-classification
What do you think?

**Comment by utoni** [comment]
Your solution seems better. Mine was just a quick fix for classification. Further dissection did not work.

**Pull request closed without merging**
