### PR TITLE
DTLS: handle (certificate) fragments

### PR DESCRIPTION
**Pull request by IvanNardi**
Keep using the existing function to handle reassembling buffer: rename it from `ndpi_search_tls_tcp_memory` to
`ndpi_search_tls_memory` and make it "transport" agnostic

### CODE REVIEW

**Comment by utoni** [comment]
I would love to have a generic reassmble interface, but #1556 is still WiP.

**Comment by IvanNardi** [comment]
> I would love to have a generic reassmble interface, but #1556 is still WiP.

@utoni , do you think we can merge this PR as-is, for the time being?

**Review by utoni — APPROVED** [review]
LGTM

**Comment by IvanNardi** [comment]
> LGTM

Thanks!

**Pull request merged**
