### PR TITLE
Fix whatsapp signature detecting.

### PR DESCRIPTION
**Pull request by vel21ripn**

### CODE REVIEW

**Comment by mmanoj** [comment]
@vel21ripn 

I found below error while running detection for whatapp. Code from git on 5th Feb 2019.

AddressSanitizer: stack-buffer-underflow ??:0 memcmp
========================================================
 #0 0x7f86cf15271f in memcmp (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x7771f)
    #1 0x7f86ce818f58 in ndpi_search_whatsapp protocols/whatsapp.c:37
    #2 0x7f86ce81455d in check_ndpi_tcp_flow_func /opt/deps/nDPI-HyperScan/nDPI/src/lib/ndpi_main.c:3957
    #3 0x7f86ce814ddf in ndpi_detection_process_packet /opt/deps/nDPI-HyperScan/nDPI/src/lib/ndpi_main.c:4573
    #4 0x7f86ce805d4e in packet_processing

Thread T2 created by T0 here:
    #0 0x7f86cf111253 in pthread_create (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x36253)

SUMMARY: AddressSanitizer: stack-buffer-underflow ??:0 memcmp
Shadow bytes around the buggy address:
  0x0ff15916b640: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ff15916b650: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ff15916b660: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ff15916b670: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ff15916b680: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0ff15916b690: 00 00 00 00[f1]f1 f1 f1 04 f4 f4 f4 f2 f2 f2 f2
  0x0ff15916b6a0: 04 f4 f4 f4 f2 f2 f2 f2 04 f4 f4 f4 f2 f2 f2 f2
  0x0ff15916b6b0: 04 f4 f4 f4 f2 f2 f2 f2 04 f4 f4 f4 f2 f2 f2 f2
  0x0ff15916b6c0: 00 f4 f4 f4 f2 f2 f2 f2 00 f4 f4 f4 f2 f2 f2 f2
  0x0ff15916b6d0: 00 f4 f4 f4 f2 f2 f2 f2 00 f4 f4 f4 f2 f2 f2 f2
  0x0ff15916b6e0: 00 f4 f4 f4 f2 f2 f2 f2 00 f4 f4 f4 f3 f3 f3 f3
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
==22678==ABORTING

**Comment by mmanoj** [comment]
Dears,
Is this fix merge ? Appreciate your update.

**Comment by k0ste** [comment]
@lucaderi, please take a look.

**Comment by mmanoj** [comment]
@lucaderi & Team,

Any update on this I was tested and no issue found.

**Comment by mmanoj** [comment]
@lucaderi 

what is the shot-stopper to merge this fix?

**Comment by lucaderi** [comment]
Thank you and I apologise for the delay merging it

**Comment by mmanoj** [comment]
@lucaderi  Thanks for the support. 

@vel21ripn  Thanks for the fix and effort. I will retest with new code and update if any issue.

**Pull request merged**
