### PR TITLE
combining nDPI and tcpdump

### PR DESCRIPTION
**Pull request by rathnaTech**
Hi all, 

nDPI is giving the deep protocol list,but tcpdump gives only the common protocol list with headers details.Is there any way to combine both for getting deep protocol headers.Please reply as soon as possible.

For example:

```
           i need header ,ttl ,payload for whatsapp,skype etc,protocols
```

Thank you

### CODE REVIEW

**Comment by kYroL01** [comment]
Hello @rathnaTech 
Sorry but I really don't understand why you're asking this into this old pull request that is already merged.

**Comment by rathnaTech** [comment]
@kYroL01 
  I expected you to discuss my question.

MY scenario is that,
 i have an idea to merge both tcpdump and nDPI (i.e i need combined result of both) for protocol and packet deep analysing.

**For example:**

using tcpdump i am getting

**___desktop:/home/nbox/nDPI-1.7/example# tcpdump -i eth0 -v
tcpdump: listening on eth0, link-type EN10MB (Ethernet), capture size 65535 bytes
15:09:23.058063 IP (tos 0x0, ttl 128, id 31390, offset 0, flags [none], proto UDP (17), length 78)
    192.168.200.101.netbios-ns > 192.168.200.255.netbios-ns: NBT UDP PACKET(137): QUERY; REQUEST; BROADCAST
15:09:23.095362 IP (tos 0x0, ttl 128, id 21358, offset 0, flags [none], proto UDP (17), length 78)
    192.168.200.172.netbios-ns > 192.168.200.255.netbios-ns: NBT UDP PACKET(137): QUERY; REQUEST; BROADCAST
15:09:23.216524 IP (tos 0x0, ttl 128, id 20214, offset 0, flags [none], proto UDP (17), length 78)
    192.168.200.109.netbios-ns > 192.168.200.255.netbios-ns: NBT UDP PACKET(137): QUERY; REQUEST; BROADCAST
15:09:23.229890 IP (tos 0x0, ttl 128, id 13210, offset 0, flags [none], proto UDP (17), length 78)
    192.168.200.120.netbios-ns > 192.168.200.255.netbios-ns: NBT UDP PACKET(137): QUERY; REQUEST; BROADCAST
15:09:23.285527 IP (tos 0x0, ttl 128, id 20215, offset 0, flags [none], proto UDP (17), length 78)
    192.168.200.109.netbios-ns > 192.168.200.255.netbios-ns: NBT UDP PACKET(137): QUERY; REQUEST; BROADCAST
15:09:23.358962 IP (tos 0x0, ttl 128, id 31391, offset 0, flags [none], proto UDP (17), length 78)
**_**
these results which includes header details like ttl,flags,length,offset etc,.

using nDPI i am getting 
**35    UDP 192.168.200.1:53 <-> 192.168.200.193:41186 [proto: 5/DNS][1 pkts/80 bytes][Host: www.windowsphone.com]
    36  UDP 192.168.200.1:53 <-> 192.168.200.193:45632 [proto: 5/DNS][1 pkts/72 bytes][Host: www.xbox.com]
    37  UDP 192.168.200.1:53 <-> 192.168.200.193:7616 [proto: 5.212/DNS.Microsoft][1 pkts/85 bytes][Host: advertising.microsoft.com]
    38  UDP 192.168.200.1:53 <-> 192.168.200.193:22592 [proto: 5/DNS][1 pkts/88 bytes][Host: 218.200.168.192.in-addr.arpa]
    39  UDP 192.168.200.1:53 <-> 192.168.200.193:29586 [proto: 5.125/DNS.Skype][1 pkts/75 bytes][Host: blogs.skype.com]
    40  UDP 192.168.200.1:53 <-> 192.168.200.193:53416 [proto: 5.120/DNS.Twitter][1 pkts/71 bytes][Host: twitter.com]
    41  UDP 192.168.200.1:53 <-> 192.168.200.193:14680 [proto: 5.119/DNS.Facebook][1 pkts/76 bytes][Host: www.facebook.com]
    42  UDP 192.168.200.1:53 <-> 192.168.200.193:32186 [proto: 5.124/DNS.YouTube][1 pkts/75 bytes][Host: www.youtube.com]**
 Here i didn't get header details for facebook,skype,youtube etc.,.

So,if i combined these to libs for getting deep protocol header details.
please suggest me the possible solutions,pros and cons.

i hope u will get my question and i am expecting some hints from you soon..

Thank you ,
kYroL01

**Comment by rathnaTech** [comment]
@kYroL01
hi sir,
Are you there.please reply

**Comment by kYroL01** [comment]
You don't see any other details as you specified because in nDPI we are not interest in these details. We are interest in flows, not single packet as a packet sniffer does.
To do what you need, we will re-think about the nucleus of nDPI. We don't need of that level of informations.
Your request is marked on packet details; we don't want to have that kind of information, is useless for this library.
If you're interest in single packet information about flag, ttl, offset, you must use a packet sniffer.

I hope you understand this.

**Comment by rathnaTech** [comment]
@kYroL01 
Hi ,
Thank you for your kind response.
  But, I am interested to analyse the details for deep protocols.So please suggest the possiblity to customize the nDPI like packet sniffer (or) Is there any way to merge packet sniffer with nDPI. I am expecting you to reply.

Note: As you said before, it is not possible to get single packet information for deep protocols right.Thats the reason i am anlaysing with nDPI.

Request: may i know your e-mail id.

Thank you

**Pull request closed without merging**
