### PR TITLE
Disable `-Wno-unused-parameter -Wno-unused-function`.

### PR DESCRIPTION
**Pull request by utoni**
* unused parameters and functions pollute the code and decrease readability

Please sign (check) the below before submitting the Pull Request:

- [x] I have signed the ntop Contributor License Agreement at https://github.com/ntop/legal/blob/main/individual-contributor-licence-agreement.md
- [x] I have read the contributing guide lines at https://github.com/ntop/nDPI/blob/dev/CONTRIBUTING.md
- [x] I have updated the documentation (in doc/) to reflect the changes made (if applicable)

Describe changes:

There are many function signatures that have unused parameters.
The ones below `src/lib/third_party` need to be treated carefully.
It may be better to enable  `-Wno-unused-parameter -Wno-unused-function` only for modules below `src/lib/third_party`.

### CODE REVIEW

**Comment by IvanNardi** [comment]
@utoni, I didn't look at your code, but I tried something similar some times ago... Removing `-Wno-unused-function` seemed feasible, but the biggest issue with ` -Wno-unused-parameter` was to have 0 warnings with and without `--enable-debug-messages` because a lot of functions have `ndpi_struct` parameter only for logging...

**Comment by utoni** [comment]
@IvanNardi, I think it makes sense to add `-Wno-unused-parameter` to the global `CFLAGS` if `--enable-debug-messages` is **not** used. I'll investigate.

**Comment by IvanNardi** [comment]
> @IvanNardi, I think it makes sense to add `-Wno-unused-parameter` to the global `CFLAGS` if `--enable-debug-messages` is **not** used. I'll investigate.

It seems reasonable

**Comment by utoni** [comment]
@IvanNardi
Could you take a look at this?
@lucaderi
This PR breaks the API.

**Review by IvanNardi — APPROVED** [review]
LGTM

**Comment by IvanNardi** [comment]
Tested by @lucaderi also on RHEL7: no issues

**Comment by utoni** [comment]
So is it ready to get merged? :D

**Pull request merged**
