### PR TITLE
 MomoChat detection signature

### PR DESCRIPTION
**Pull request by mmanoj**
Please arrange to merge the subject change

### CODE REVIEW

**Comment by mmanoj** [comment]
Please arrange to merge the latest files uploaded.

**Comment by mmanoj** [comment]
Dear nDPI Team,

Any update on merge above change.

**Comment by mmanoj** [comment]
Dear Team,
Please arrange to merge this fix.

**Comment by lucaderi** [comment]
I prefer to keep off nDPI protocols that are not that popular, and leave in the engine only the popular protocols. You can define (as we do for many EU protocols not used elsewhere) a protocols.txt file and put it there. This way the engine is kept compact while leaving people the freedom to add new protocols.

**Comment by mmanoj** [comment]
@lucaderi 

Thanks for the advice and way forward. I will use as instructed. If any other protocols/services in your list, please let me know to contribute.

**Pull request closed without merging**
