### PR TITLE
Mqtt dissector fix

### PR DESCRIPTION
**Pull request by srzamfir**
Fixed the Mqtt dissector. No more false positives on skype, kakaotalk and http.
However there are some issues with CoAP :

@kYroL01 : You have modified the CoAP dissector and also the Dropbox one in this commit a594273.
Please consider reverting the Dropbox changes since the actual  coap_mqtt.pcap doesn't contain any Dropbox traffic and thus the coap_mqtt.pcap test will fail. I've uploaded the correct test results (the pcap trace contains only traffic between 4 CoAP clients and 4 Mqtt clients - handcrafted by me - that generate traffic according to a predefined scenario so 800 CoAP packets is correct !)

Also, please do not rely solely on Wireshark for correct identification because it only considers the ports (in this specific test case the ports were randomly chosen by me (17500, 17501) to actually test nDPIs deep packet inspection capabilities for identifying CoAP and MQTT traffic that doesn't run on standard ports).

Cheers,
Sorin

### CODE REVIEW

**Comment by kYroL01** [comment]
@srzamfir Ok I fix the Dropbox as u explain. The problem is that your CoAP dissector created false positive for BitTorrent as explain in this issue https://github.com/ntop/nDPI/issues/164.
So I changed to fix this bug.
I also did test with a Dropbox pcap sniffing traffic from my host and everything was detected as CoAp, wrongly.
Now I check your pull request, thanks.

**Comment by srzamfir** [comment]
@kYroL01 If the CoAP dissector creates false positives with other traces this means it requires further fine-tuning. I'll also take a look at the mentioned bug.

**Comment by kYroL01** [comment]
The fix I made solved the problem for BT. 
Now I'm testing your pull request before merge.

**Comment by kYroL01** [comment]
I fixed Dropbox, tested your pull request and I think is correct.
Thank you

**Pull request merged**
