### PR TITLE
ahocorasick: fix char/uchar bug

### LINKED ISSUE #1506: Issue in automata release
`
Program terminated with signal SIGABRT, Aborted.
#0  0x00007fba2dc187bb in raise () from /lib/x86_64-linux-gnu/libc.so.6
[Current thread is 1 (Thread 0x7fba2d4be400 (LWP 2275))]
(gdb) bt
#0  0x00007fba2dc187bb in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007fba2dc03535 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007fba2dc5a508 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#3  0x00007fba2dc60c1a in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#4  0x00007fba2dc6242c in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#5  0x00007fba2e999e7d in node_release_pattern (thiz=0x563e360ab600) at third_party/src/ahocorasick.c:771
#6  node_release (thiz=0x563e360ab600, free_pattern=<optimized out>) at third_party/src/ahocorasick.c:786
#7  0x00007fba2e999eff in ac_automata_release_node (thiz=thiz@entry=0x563e360b0380, n=n@entry=0x563e360ab600, idx=idx@entry=0, data=data@entry=0x1) at third_party/src/ahocorasick.c:544
#8  0x00007fba2e99aa98 in ac_automata_walk (thiz=0x563e360b0380, node_cb=node_cb@entry=0x7fba2e999ed0 <ac_automata_release_node>, alpha_cb=alpha_cb@entry=0x0, data=data@entry=0x1)
    at third_party/src/ahocorasick.c:288
#9  0x00007fba2e99b3ab in ac_automata_release (thiz=0x563e360b0380, free_pattern=<optimized out>) at third_party/src/ahocorasick.c:556
`
`
(gdb) frame 5
#5  0x00007fba2e999e7d in node_release_pattern (thiz=0x563e360ab600)
    at third_party/src/ahocorasick.c:771
771	third_party/src/ahocorasick.c: No such file or directory.
`
`
(gdb) p *thiz
$1 = {id = 10, one_alpha = 0 '\000', one = 0 '\000', range = 0 '\000', 
  root = 0 '\000', final = -1 '\377', use = 0 '\000', ff = -1 '\377', 
  depth = 9, matched_patterns = 0x563e360b1480, outgoing = 0x0, 
  failure_node = 0x563e360a1340, a_ptr = 0x0}
(gdb) p *thiz->matched_patterns 
$2 = {num = 1, max = 8, patterns = 0x563e360b1488}
`
`
(gdb) p *thiz->matched_patterns->patterns 
$3 = {astring = 0x7ffe7074c40e "apple.com", length = 9, is_existing = 0, 
  rep = {number = 1, number64 = 0, breed = 0, category = 0, level = 0, 
    from_start = 0, at_end = 0, dot = 0}}
`

### PR DESCRIPTION
**Pull request by IvanNardi**
Porting of https://github.com/vel21ripn/nDPI/commit/06e2967d0c26ab214683a2f5565f4012fd523537
Close #1506

### CODE REVIEW

**Comment by IvanNardi** [comment]
@vel21ripn , could you take a look, please?

**Comment by IvanNardi** [comment]
@vel21ripn, kindly pinging...

**Comment by vel21ripn** [comment]
It feels good.
I must have accidentally missed this notification in the mail :(

**Comment by IvanNardi** [comment]
> It feels good. I must have accidentally missed this notification in the mail :(

Thanks for the feedback!

**Pull request merged**
