### PR TITLE
H323: improve detection and avoid false positives

### PR DESCRIPTION
**Pull request by IvanNardi**

### CODE REVIEW

**Comment by 0xA50C1A1** [comment]
Hi, I was just reworking this dissector :) Here is my solution if you want to take a look

[h323_patch.zip](https://github.com/ntop/nDPI/files/15271419/h323_patch.zip)

**Comment by IvanNardi** [comment]
> Hi, I was just reworking this dissector :) Here is my solution if you want to take a look
> 
> [h323_patch.zip](https://github.com/ntop/nDPI/files/15271419/h323_patch.zip)

Welcome back!! I'll look into that later, thanks!

**Comment by 0xA50C1A1** [comment]
> > Hi, I was just reworking this dissector :) Here is my solution if you want to take a look
> > [h323_patch.zip](https://github.com/ntop/nDPI/files/15271419/h323_patch.zip)
> 
> Welcome back!! I'll look into that later, thanks!

Yeah, finally the support figured out what was wrong and removed the restrictions from me.

**Review by utoni — APPROVED** [review]

**Comment by IvanNardi** [comment]
> > Hi, I was just reworking this dissector :) Here is my solution if you want to take a look
> > [h323_patch.zip](https://github.com/ntop/nDPI/files/15271419/h323_patch.zip)
> 
> Welcome back!! I'll look into that later, thanks!

I integrated your changes, but I kept the check on the udp ports

**Pull request merged**
