### PR TITLE
:bulb: implement WebSocket protocol dissector

### LINKED ISSUE #882: Add Websocket protocol support

### PR DESCRIPTION
**Pull request by leonn**
Closes #882 
Add WebSocket protocol dissector
Update tests results

### CODE REVIEW

**Comment by lucaderi** [comment]
Hi Leonn thanks for the contribution. Unfortunately I see that your code generates many false positives
Example
213	TCP 147.234.1.253:21 -> 84.168.1.2:2720 [proto: 251/WEBSOCKET][cat: Web/5][1 pkts/73 bytes -> 0 pkts/0 bytes][Goodput ratio: 26/0][< 1 sec][PLAIN TEXT (200 Type set to I)]
 	214	TCP 192.168.1.2:2720 -> 147.117.1.253:21 [proto: 251/WEBSOCKET][cat: Web/5][1 pkts/73 bytes -> 0 pkts/0 bytes][Goodput ratio: 26/0][< 1 sec][PLAIN TEXT (RETR Site)]
 	215	TCP 192.168.1.2:2679 -> 147.234.1.253:21 [proto: 251/WEBSOCKET][cat: Web/5][1 pkts/66 bytes -> 0 pkts/0 bytes][Goodput ratio: 18/0][< 1 sec][PLAIN TEXT (PASS d0)]

Can you fix them please?

**Comment by leonn** [comment]
OK I will investigate and submit the improvements

**Comment by leonn** [comment]
rewrote the WebSocket detection, @lucaderi  now there are no false positives.

**Comment by lucaderi** [comment]
Great work! Thank you

**Pull request merged**
