### PR TITLE
Add UFTP protocol dissector

### PR DESCRIPTION
**Pull request by 0xA50C1A1**
Please sign (check) the below before submitting the Pull Request:

- [x] I have signed the ntop Contributor License Agreement at https://github.com/ntop/legal/blob/main/individual-contributor-licence-agreement.md
- [x] I have read the contributing guide lines at https://github.com/ntop/nDPI/blob/dev/CONTRIBUTING.md
- [x] I have updated the documentation (in doc/) to reflect the changes made (if applicable)

Describe changes:

UFTP is a multicast file transfer protocol with encryption support.

### CODE REVIEW

**Review by IvanNardi — COMMENTED** [review]
Are you able to merge the two pcap files into (only) one?

**Comment by 0xA50C1A1** [comment]
> Are you able to merge the two pcap files into (only) one?

Ok, done.

**Comment by IvanNardi** [comment]
> > Are you able to merge the two pcap files into (only) one?
> 
> Ok, done.

Thanks!

**Review by IvanNardi — APPROVED** [review]
Thank you

**Pull request merged**
