### PR TITLE
Fix missing bracket at ppstream

### PR DESCRIPTION
**Pull request by egecetin**

### CODE REVIEW

**Comment by IvanNardi** [comment]
The change makes a lot of sense...
How did you find it? Do you have a pcap triggering the issue?

**Comment by egecetin** [comment]
TBH, I don't have any `pcap` file for `ppstream` or any environment on my machine for nDPI. I found this while statically analyzing some open-source projects (of course one of them is nDPI). It gives a warning because other if conditions (for example `else if(packet->payload[2] == 0x44)` condition) are under the `if(packet->payload[2] == 0x43)` line. I wanted to check using your CI but currently it fails (probably since you have an ongoing development at dev branch)

**Comment by IvanNardi** [comment]
CI has been fixed. Could you rebase, please?

**Review by IvanNardi — APPROVED** [review]

**Comment by IvanNardi** [comment]
@egecetin , could you update the unit test result?
Otherwise, I can easily take care of it while merging; not a problem...

**Comment by egecetin** [comment]
May I ask you a favor for unit testing :). If you can update it can be quite helpful for me because I can't run manually on my local machine/computer. I can try but it can take some time to fix completely

**Comment by IvanNardi** [comment]
Ok. I'll do it. Could you please check the box "Allow edits from maintainers" (from the PR main page) to allow me to push to your PR?
(if you are interested: https://tighten.com/blog/adding-commits-to-a-pull-request/)

**Comment by egecetin** [comment]
It is already checked. Thanks

**Comment by IvanNardi** [comment]
Good catch, @egecetin! Thanks for taking the time to push this fix upstream.

**Pull request merged**
