### PR TITLE
Added `--enable-code-coverage' build using lcov for coverage generation.

### PR DESCRIPTION
**Pull request by utoni**
* CI job generates a coverage report

Signed-off-by: Toni Uhlig <matzeton@googlemail.com>

### CODE REVIEW

**Comment by utoni** [comment]
This PR generates a HTML based code coverage report and uploads it as CI artifact. It can be viewed locally for now. It is also possible to use third party services e.g. [codecov.io](https://codecov.io) but not implemented yet. The report literally shows how badly libnDPI's code is tested.

**Comment by lucaderi** [comment]
Interesting contribution

**Comment by IvanNardi** [comment]
> This PR generates a HTML based code coverage report and uploads it as CI artifact. It can be viewed locally for now. It is also possible to use third party services e.g. [codecov.io](https://codecov.io) but not implemented yet. The report literally shows how badly libnDPI's code is tested.

@lnslbrty : I haven't yet looked at this report.
oss-fuzz generates something similar (https://storage.googleapis.com/oss-fuzz-coverage/ndpi/reports/20220227/linux/report.html; the link should be public).
The results seem similar to what you have found: good average coverage for dissector code; non-existent coverage for common code

**Comment by utoni** [comment]
> > This PR generates a HTML based code coverage report and uploads it as CI artifact. It can be viewed locally for now. It is also possible to use third party services e.g. [codecov.io](https://codecov.io) but not implemented yet. The report literally shows how badly libnDPI's code is tested.
> 
> @lnslbrty : I haven't yet looked at this report. oss-fuzz generates something similar (https://storage.googleapis.com/oss-fuzz-coverage/ndpi/reports/20220227/linux/report.html; the link should be public). The results seem similar to what you have found: good average coverage for dissector code; non-existent coverage for common code

I think that a code coverage percentage generated from fuzzing may be misleading, because it is basically a non-reproducible random value that may vary with every execution / on every device.
I would prefer generating code coverage from integration or better unit tests.

**Pull request merged**
