### PR TITLE
New version of the ahocorasick library

### PR DESCRIPTION
**Pull request by vel21ripn**
The new version is about 25% faster with -O2 and 45% faster with -O3.
No recursion is used (smaller stack size required).
Uses less memory (by valgrind info)
 bigram:
  - original 1796 allocs,   247864 bytes allocated
  - new      1232 allocs,   158880 bytes allocated
 host_match:
  - original 18038 allocs, 3004576 bytes allocated
  - new       6861 allocs,  396624 bytes allocated

The function ac_automata_search() is thread safe.
Optional case-insensitive comparison.
Matching at the beginning and at the end of the string is supported.
One code file and one header file.

### CODE REVIEW

**Comment by lucaderi** [comment]
This looks like a great performance contribution!

**Comment by lucaderi** [comment]
@vel21ripn Your patch has created this new issue

==29215==ERROR: AddressSanitizer: stack-use-after-scope on address 0x7ffd41813b20 at pc 0x0000004cfb5b bp 0x7ffd418139b0 sp 0x7ffd41813160
asan_interceptors.cc.o:?
/home/tests/nDPI/src/lib/third_party/src/ahocorasick.c:888
/home/tests/nDPI/src/lib/third_party/src/ahocorasick.c:653
/home/tests/nDPI/src/lib/third_party/src/ahocorasick.c:272
/home/tests/nDPI/src/lib/third_party/src/ahocorasick.c:361

Can you please find a solution?

**Comment by vel21ripn** [comment]
How to reproduce this testing? Testing with "Configure --with-Sanitizer" did not reveal errors.

**Comment by lucaderi** [comment]
@cardigliano Can you please explain how you have reproduced this issue?

**Comment by vel21ripn** [comment]
What version of the compiler build a project. Flags for the compiler, options for сonfigure.

**Comment by cardigliano** [comment]
I was able to reproduce this by running the ntopng (which is using nDPI) regression tests as explained at:
https://github.com/ntop/ntopng/blob/dev/CONTRIBUTING.md#memory-leak-detection

**Comment by cardigliano** [comment]
In short:

cd ntopng
./autogen.sh
./configure --with-sanitizer
make
cd tests/rest
./run.sh

(all the tests will fail with the error, reproduced on Ubuntu 18 LTS)

**Comment by vel21ripn** [comment]
I thought that this problem was detected when testing nDPI!
I will try to collect ntopng.

**Comment by vel21ripn** [comment]
I was able to successfully build "ntopng" under slackware-14.2.
I was getting ntopng crashing when libnl-1.1.4 was present on the system. Removing the package and rebuilding gave a workable ntopng.
So far I am getting messages about memory leaks on all tests.
```
[>] Running test 'alert_flow_risk_missing_tls_sni' (9/45)
[!]  ntopng Error: ntopng generated errors or warnings running 'alert_flow_risk_missing_tls_sni'
==8658==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 64 byte(s) in 1 object(s) allocated from:
/tmp/llvm-11.1.0.src/build/../projects/compiler-rt/lib/asan/asan_malloc_linux.cpp:154
??:0
??:0
??:0
Direct leak of 36 byte(s) in 1 object(s) allocated from:
/tmp/llvm-11.1.0.src/build/../projects/compiler-rt/lib/asan/asan_malloc_linux.cpp:145
??:0
??:0
Direct leak of 14 byte(s) in 1 object(s) allocated from:
/tmp/llvm-11.1.0.src/build/../projects/compiler-rt/lib/asan/asan_malloc_linux.cpp:145
??:0
Direct leak of 8 byte(s) in 1 object(s) allocated from:
/tmp/llvm-11.1.0.src/build/../projects/compiler-rt/lib/asan/asan_malloc_linux.cpp:154
??:0
??:0
??:0
Indirect leak of 56 byte(s) in 10 object(s) allocated from:
/tmp/llvm-11.1.0.src/build/../projects/compiler-rt/lib/asan/asan_malloc_linux.cpp:145
??:0
Indirect leak of 16 byte(s) in 1 object(s) allocated from:
/tmp/llvm-11.1.0.src/build/../projects/compiler-rt/lib/asan/asan_malloc_linux.cpp:154
```

The situation does not change if the "src/lib/libndpi.a" library is built without "--with-sanitizer"
I am unable to build these projects in ubuntu at the moment. 
Maybe tomorrow I can build nDPI & ntopng for ubuntu.

**Comment by vel21ripn** [comment]
I added the missing GeoLite2-ASN.mmdb file and the memory leak stopped.

**Comment by vel21ripn** [comment]
Ubuntu 18.0.4 LTS clang-10
Bugs:
* Missing file ntopng/third-party/zeromq-4.1.7/configure.ac
* commit c429baeb64e0668389df91c10f01a9e4b818d423 missing check NTOPNG_PRO
```
diff --git a/src/AutonomousSystem.cpp b/src/AutonomousSystem.cpp
index 75f3833..f03cf20 100644
--- a/src/AutonomousSystem.cpp
+++ b/src/AutonomousSystem.cpp
@@ -28,7 +28,9 @@
 AutonomousSystem::AutonomousSystem(NetworkInterface *_iface, IpAddress *ipa) : GenericHashEntry(_iface), GenericTrafficElement(), Score(_iface) {
   asname = NULL;
   round_trip_time = 0;
+#ifdef NTOPNG_PRO
   nextMinPeriodicUpdate = 0;
+#endif
   ntop->getGeolocation()->getAS(ipa, &asn, &asname);
 
 #ifdef AS_DEBUG
diff --git a/src/NetworkInterface.cpp b/src/NetworkInterface.cpp
index aece483..3679801 100644
--- a/src/NetworkInterface.cpp
+++ b/src/NetworkInterface.cpp
@@ -3149,7 +3149,9 @@ void NetworkInterface::periodicStatsUpdate() {
   ntop->getTrace()->traceEvent(TRACE_NORMAL, "Stats update done [took: %d]", tdebug.tv_sec - tdebug_init.tv_sec);
 #endif
 
+#ifdef NTOPNG_PRO
   updateBehaviorStats(&tv);
+#endif
 }
 
 /* *************************************** */
```

Commit cb32c3f64d5d66005639226dc7f70d95cebcd48d built without errors.

### What commit did you get errors on?

**Comment by cardigliano** [comment]
Please note the error is stack-use-after-scope, and the piece of code triggering this is adding to the automa a string defined in a block, which is invalid out of that block. The question is: does ndpi_add_string_to_automa expect a malloc'ed string or does it take care of doing a strdup?

Example:

{
    char str[255];
    snprintf(str, sizeof(str), "%s", "xxx");
    ndpi_add_string_to_automa(automa, str);
}

ndpi_finalize_automa(whitelist_automa); <- stack-use-after-scope

Looking at the code, it seems a malloc'ed string is required, however I've seen calls to ndpi_add_string_to_automa doing a strdup (leak?).

**Comment by vel21ripn** [comment]
ndpi_add_string_to_automa() does not duplicate a string via strdup().
I have not yet changed the code executed by ac_automata_add() when updating libahocorasick.
Please post the maxmind bases with which you are testing the code of the ntopng project somewhere. I updated them yesterday and now more than half of the tests come with errors.

**Comment by vel21ripn** [comment]
void Ntop::loadTrackers() use ndpi_add_string_to_automa() without strdup().

**Pull request merged**
