### PR TITLE
Add more tracker/ad hosts

### PR DESCRIPTION
**Pull request by 0xA50C1A1**
Please sign (check) the below before submitting the Pull Request:

- [x] I have signed the ntop Contributor License Agreement at https://github.com/ntop/legal/blob/main/individual-contributor-licence-agreement.md
- [x] I have read the contributing guide lines at https://github.com/ntop/nDPI/blob/dev/CONTRIBUTING.md
- [x] I have updated the documentation (in doc/) to reflect the changes made (if applicable)

Describe changes:

Add some big tracking/advertising networks

### CODE REVIEW

**Comment by 0xA50C1A1** [comment]
@IvanNardi @utoni Well, it's only a small part of the entire list I got, and I can share the rest if it would be useful.

**Comment by 0xA50C1A1** [comment]
It's strange that such small changes caused the fuzzing test failure.

**Review by IvanNardi — APPROVED** [review]

**Comment by IvanNardi** [comment]
> It's strange that such small changes caused the fuzzing test failure.

It is an unrelated issue that keep popping up in the fuzzer
```
    #3 0x5c6331 in ndpi_strdup /src/ndpi/src/lib/ndpi_memory.c:113:13
    #4 0x58dc7c in ndpi_add_host_risk_mask /src/ndpi/src/lib/ndpi_main.c:4247:14
    #5 0x592605 in ndpi_handle_rule /src/ndpi/src/lib/ndpi_main.c:4344:11
    #6 0x592605 in load_protocols_file_fd /src/ndpi/src/lib/ndpi_main.c:5036:8
```
Completely unrelated to this PR

**Comment by IvanNardi** [comment]
> @IvanNardi @utoni Well, it's only a small part of the entire list I got, and I can share the rest if it would be useful.

How big is that list?
* 10-100 entries? Go ahead and put in in `src/lib/ndpi_content_match.c.inc`
*  a lot bigger than 100? I think we need to think about that. I don't think we want to have "pihole" long lists embedded in the code. It is always the same issue as gambling, telemetry...

**Review by IvanNardi — APPROVED** [review]
thank you

**Comment by 0xA50C1A1** [comment]
> > @IvanNardi @utoni Well, it's only a small part of the entire list I got, and I can share the rest if it would be useful.
> 
> How big is that list?
> 
>     * 10-100 entries? Go ahead and put in in `src/lib/ndpi_content_match.c.inc`
> 
>     * a lot bigger than 100? I think we need to think about that. I don't think we want to have "pihole" long lists embedded in the code. It is always the same issue as gambling, telemetry...

About 80 entries.

**Comment by IvanNardi** [comment]
> > > @IvanNardi @utoni Well, it's only a small part of the entire list I got, and I can share the rest if it would be useful.
> > 
> > 
> > How big is that list?
> > ```
> > * 10-100 entries? Go ahead and put in in `src/lib/ndpi_content_match.c.inc`
> > 
> > * a lot bigger than 100? I think we need to think about that. I don't think we want to have "pihole" long lists embedded in the code. It is always the same issue as gambling, telemetry...
> > ```
> 
> About 80 entries.

Ok, add them as this PR (if you want, of course)

**Comment by 0xA50C1A1** [comment]
> > > > @IvanNardi @utoni Well, it's only a small part of the entire list I got, and I can share the rest if it would be useful.
> > > 
> > > 
> > > How big is that list?
> > > ```
> > > * 10-100 entries? Go ahead and put in in `src/lib/ndpi_content_match.c.inc`
> > > 
> > > * a lot bigger than 100? I think we need to think about that. I don't think we want to have "pihole" long lists embedded in the code. It is always the same issue as gambling, telemetry...
> > > ```
> > 
> > 
> > About 80 entries.
> 
> Ok, add them as this PR (if you want, of course)

Sure.

**Pull request merged**
