### PR TITLE
IPv6: fix bad ipv6 format (#1890)

### LINKED ISSUE #1890: A bug with ipv6 address format
## Describe the bug
Because ndpi_patchIPv6Address will replace all :0: to ::, the results may have ip like this 2600:1901::16a9:: . It's a wrong ipv6 format, it has multiple '::'

### PR DESCRIPTION
**Pull request by paolomonti**
Please sign (check) the below before submitting the Pull Request:

- [x] I have signed the ntop Contributor License Agreement at https://github.com/ntop/legal/blob/main/individual-contributor-licence-agreement.md
- [x ] I have read the contributing guidelines at https://github.com/ntop/nDPI/blob/dev/CONTRIBUTING.md
- [x] I have updated the documentation (in doc/) to reflect the changes made (if applicable)

Link to the related [issue](https://github.com/ntop/nDPI/issues):

Describe changes:
Fixes #1890 
IPv6 addresses already containing "::" token shall not be searched for ":0:" nor patched,
therefore ndpi_patchIPv6Address returns immediately in case "::" is found.

### CODE REVIEW

**Comment by IvanNardi** [comment]
@paolomonti, could you sign the CLA, please?

**Comment by IvanNardi** [comment]
@paolomonti, could you update the unit tests results, please?
Something like:
``` 
NDPI_FORCE_UPDATING_UTESTS_RESULTS=1 ./tests/do.sh
```
and commit the modified files

**Comment by paolomonti** [comment]
tests ok, cla sent

**Review by IvanNardi — APPROVED** [review]

**Comment by IvanNardi** [comment]
@paolomonti, thanks for your contribution!

**Pull request merged**
