### PR TITLE
Added a few new lines in ndpi_content_match.c.inc

### PR DESCRIPTION
**Pull request by zehranurozbay**

### CODE REVIEW

**Comment by IvanNardi** [comment]
@zehraIn, could you update the tests results please? [see https://github.com/ntop/nDPI/actions/runs/5112441574/jobs/9190504397?pr=1997 for example]

**Comment by zehranurozbay** [comment]
> @zehraIn, could you update the tests results please? [see https://github.com/ntop/nDPI/actions/runs/5112441574/jobs/9190504397?pr=1997 for example]

"Hi, I'm new around here and I can't figure out what I should do. The project is working on my local machine.

**Comment by utoni** [comment]
> > @zehraIn, could you update the tests results please? [see https://github.com/ntop/nDPI/actions/runs/5112441574/jobs/9190504397?pr=1997 for example]
> 
> "Hi, I'm new around here and I can't figure out what I should do. The project is working on my local machine.

Type in your terminal (inside the `nDPI` project):

```shell
rm tests/cfgs/*/result/*.out && \
    NDPI_DISABLE_FUZZY=1 ./tests/do.sh && \
    git add tests/cfgs && \
    git commit --amend && \
    git push --force-with-lease # add your github remote if required
```

If you do not know your git remote: look it up with `git remote -v`.

That should do the trick.

**Comment by IvanNardi** [comment]
Something is seriously wrong... all the results file have been removed

**Comment by IvanNardi** [comment]
@zehraIn, are you going to push a new PR? It was interesting stuff...

**Comment by zehranurozbay** [comment]
I'll try

**Comment by IvanNardi** [comment]
> I'll try

With latest dev, to update the unit tests results, you can `FORCE_UPDATING_UTESTS_RESULTS=1 ./tests/do.sh` and then add/push all the changed files...

**Pull request closed without merging**
