### PR TITLE
2.0 stable

### PR DESCRIPTION
**Pull request by subhedarnikhil**
Hi Reviewer,
Please find atatched code for soundcloud.com support.

[support_for_sound_cloud.zip](https://github.com/ntop/nDPI/files/1067956/support
[support_for_sound_cloud.zip](https://github.com/ntop/nDPI/files/1067957/support_for_sound_cloud.zip)
_for_sound_cloud.zip)

### CODE REVIEW

**Comment by kYroL01** [comment]
I have to check due to some conflicts that seems to be.
Thanks

**Comment by subhedarnikhil** [comment]
what i will have to do now for the same?

**Comment by alagoutte** [comment]
Hi,

it is not possible to push a better PR ? because there is some old file..

**Comment by kYroL01** [comment]
@alagoutte I could change by myself, I saw modification in zip file.
@subhedarnikhil I close this pull request because you sent in a wrong way, but I push your contribution in new commit.

Thanks

**Comment by subhedarnikhil** [comment]
@kYroL01: I will checkout the fresh code and merge those changes and shall send you the updated code with new pull request

**Pull request closed without merging**
