### PR TITLE
High level API and ndpiReader simplification

### PR DESCRIPTION
**Pull request by emanuele-f**
Migrates potentially reusable code from ndpiReader to ndpi_util module to promote a clean and fast nDPI integration

### CODE REVIEW

**Comment by kYroL01** [comment]
@emanuele-f Thanks for the huge work. The commit is big and before merging I need to check if all is correct and understand the changes.

**Comment by lucaderi** [comment]
@emanuele-f Many thanks for your work. The code is much more readable now.

**Comment by emanuele-f** [comment]
Thank you for supporting this project!

**Comment by lucaderi** [comment]
@emanuele-f Shall you be interested in joining the nDPI developers group, please drop me a mail. We need help!

**Comment by mmanoj** [comment]
can you guide me where it really taking flow->host_server_name as (ndpi_util.c) I observed host name not correctly printed corresponding to detected protocol as below example:

| Src: TCP 10.130.0.28:40962 | Dest: 74.125.200.113:80 | [proto: 7.126/HTTP.Google] | [proto: 126/Google] | [7 pkts/478 bytes] | [Host: packages.linuxmint.com] | [SSL client: ] | [SSL server: ]

**Comment by lucaderi** [comment]
@mmanoj I have tried with the version in git and this is what I get
    1   TCP 192.168.1.5:49499 <-> 68.235.39.11:80 [proto: 7/HTTP][20 pkts/11677 bytes][Host: packages.linuxmint.com]

Whereas if I I do a reverse lookup of the IP 74.125.200.113 I get, so in essence is hosted on the google CDN as reported by nDPI

NetRange:       74.125.0.0 - 74.125.255.255
CIDR:           74.125.0.0/16
NetName:        GOOGLE
NetHandle:      NET-74-125-0-0-1
Parent:         NET74 (NET-74-0-0-0-0)
NetType:        Direct Allocation
OriginAS:
Organization:   Google Inc. (GOGL)
RegDate:        2007-03-13
Updated:        2012-02-24
Ref:            https://whois.arin.net/rest/net/NET-74-125-0-0-1

**Comment by mmanoj** [comment]
Thanks Dr.Luca for quick reply. It mean in my case it's reverse lookup ? I will do more test and update you.

Thank you,
Manoj

**Comment by mmanoj** [comment]
@lucaderi 

One more test example as below:
 | Src: TCP 10.130.0.70:51060 | Dest: 31.13.79.220:443 | [proto: 91.119/SSL.Facebook] | [proto: 119/Facebook] | [4 pkts/763 bytes] | [Host: play.google.com] | [SSL client: www.facebook.com] | [SSL server: ]

**Pull request merged**
