### PR TITLE
ndpi_strnstr optimization

### PR DESCRIPTION
**Pull request by 0xA50C1A1**
Please sign (check) the below before submitting the Pull Request:

- [x] I have signed the ntop Contributor License Agreement at https://github.com/ntop/legal/blob/main/individual-contributor-licence-agreement.md
- [x] I have read the contributing guide lines at https://github.com/ntop/nDPI/blob/dev/CONTRIBUTING.md
- [x] I have updated the documentation (in doc/) to reflect the changes made (if applicable)

Describe changes:

On average, the new implementation is 2.5 times faster. Although, of course, there are test cases where it shows slightly worse results.

Also I wrote a small [benchmark](https://github.com/ntop/nDPI/files/15272200/benchmark.zip) to compare different implementations if you're interested.

### CODE REVIEW

**Review by IvanNardi — CHANGES_REQUESTED** [review]
Could you
* add the benchmark code in `tests/performance/`, updating the makefile, please?
* add some unit tests (expecially, some corner cases) in `example/ndpiReader.c`, like you did for `strlcpy`?

**Comment by 0xA50C1A1** [comment]
> Could you
> 
>     * add the benchmark code in `tests/performance/`, updating the makefile, please?

original one or try to rewrite it in C?

**Comment by IvanNardi** [comment]
> original one or try to rewrite it in C?

Original one!

**Comment by 0xA50C1A1** [comment]
> > original one or try to rewrite it in C?
> 
> Original one!

Ok, sure.

**Review by IvanNardi — APPROVED** [review]
Thanks!

**Pull request merged**
