### PR TITLE
fix broken sanitizer CFLAGS, --enable-fuzztargets should also set -fs…

### PR DESCRIPTION
**Pull request by utoni**
…anitize

Signed-off-by: Toni Uhlig <matzeton@googlemail.com>

Can you verify if that works for Mac OS X as well. Thanks!

### CODE REVIEW

**Comment by lucaderi** [comment]
Thanks

**Comment by IvanNardi** [comment]
This commit probably broke configure script with --with-sanitizer flag and an external CFLAGS variable.
On my enviroment (ubuntu 18.04):

```
i@latitude:~/svnrepos/nDPI2(dev)$ ./autogen.sh >/dev/null 2>&1
i@latitude:~/svnrepos/nDPI2(dev)$ CFLAGS="-W" ./configure --with-sanitizer
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking how to print strings... printf
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/home/ivan/svnrepos/nDPI2':
configure: error: C compiler cannot create executables
See `config.log' for more details
```

Full log attached. 
[config.log](https://github.com/ntop/nDPI/files/4885160/config.log)


Reverting this commit, everything seems to be ok
Am I doing something wrong here?

**Comment by lucaderi** [comment]
Something went wrong as travis reported, but I don't have time to check now. @lnslbrty What do you think?

**Comment by utoni** [comment]
I'm on it.

**Comment by IvanNardi** [comment]
> This commit probably broke configure script with --with-sanitizer flag and an external CFLAGS variable.

Any news on this issue?

**Comment by utoni** [comment]
Does #965 fix that issue for you?

**Comment by lucaderi** [comment]
Working now on MacOS

**Pull request merged**
