### PR TITLE
fix dissector QQ unkown bug

### PR DESCRIPTION
**Pull request by xumjbn**
hi：
    I am using nDPI for some test, and I found the QQ dissector didn't work, and I fix it.

Here is the qq.pcap file what I am tested: http://pan.baidu.com/s/1eQx1g8E

### CODE REVIEW

**Comment by kYroL01** [comment]
Can you please send again a pcap in another way ? I cannot download it. and is in chinese, so impossibile for me to understand :)
You patch seems to be good. Thank you.

**Comment by xumjbn** [comment]
You are wellcome, Mabye I can send the pcap file with email, but I do not have your email address.If you can provide a email address, I will send you the test pcap file.

**Comment by xumjbn** [comment]
https://onedrive.live.com/redir?resid=D7065D367BA1CBE3!108&authkey=!AA6EFIQkdJZiMJ8&ithint=file%2cpcap

**Comment by kYroL01** [comment]
I downloaded! Thank you

**Pull request merged**
