### PR TITLE
IFLIX service add

### PR DESCRIPTION
**Pull request by mmanoj**
IFLIX service added, Please review and merge. This is by www.vizuamatix.com R&D team

```
UDP 192.168.1.1:53 <-> 192.168.1.105:16069 [proto: 5.216/DNS.IFLIX][1 pkts/73 bytes][Host: www.iflix.com]
26  UDP 192.168.1.1:53 <-> 192.168.1.105:12694 [proto: 5.216/DNS.IFLIX][1 pkts/73 bytes][Host: www.iflix.com]
27  UDP 192.168.1.1:53 <-> 192.168.1.105:50259 [proto: 5.216/DNS.IFLIX][1 pkts/73 bytes][Host: www.iflix.com]
28  TCP 192.168.1.105:58010 <-> 54.230.159.246:443 [proto: 91.216/SSL.IFLIX][4 pkts/481 bytes][SSL client: www.iflix.com]
42  TCP 192.168.1.105:58208 <-> 54.230.159.246:443 [proto: 91.216/SSL.IFLIX][4 pkts/797 bytes][SSL client: www.iflix.com]
43  TCP 192.168.1.105:58206 <-> 54.230.159.246:443 [proto: 91.216/SSL.IFLIX][4 pkts/797 bytes][SSL client: www.iflix.com]
44  TCP 192.168.1.105:58212 <-> 54.230.159.246:443 [proto: 91.216/SSL.IFLIX][4 pkts/797 bytes][SSL client: www.iflix.com]
45  TCP 192.168.1.105:58210 <-> 54.230.159.246:443 [proto: 91.216/SSL.IFLIX][4 pkts/797 bytes][SSL client: www.iflix.com]
46  TCP 192.168.1.105:58214 <-> 54.230.159.246:443 [proto: 91.216/SSL.IFLIX][4 pkts/797 bytes][SSL client: www.iflix.com]
47  TCP 192.168.1.105:58314 <-> 54.230.159.246:443 [proto: 91.216/SSL.IFLIX][4 pkts/797 bytes][SSL client: www.iflix.com]
48  TCP 192.168.1.105:58310 <-> 54.230.159.246:443 [proto: 91.216/SSL.IFLIX][4 pkts/797 bytes][SSL client: www.iflix.com]
49  TCP 192.168.1.105:58318 <-> 54.230.159.246:443 [proto: 91.216/SSL.IFLIX][4 pkts/797 bytes][SSL client: www.iflix.com]
50  TCP 192.168.1.105:58316 <-> 54.230.159.246:443 [proto: 91.216/SSL.IFLIX][4 pkts/797 bytes][SSL client: www.iflix.com]
51  TCP 192.168.1.105:58312 <-> 54.230.159.246:443 [proto: 91.216/SSL.IFLIX][4 pkts/797 bytes][SSL client: www.iflix.com]
53  UDP 192.168.1.1:53 <-> 192.168.1.105:50615 [proto: 5.216/DNS.IFLIX][1 pkts/85 bytes][Host: feature-service.iflix.com]
54  UDP 192.168.1.1:53 <-> 192.168.1.105:38605 [proto: 5.216/DNS.IFLIX][1 pkts/85 bytes][Host: feature-service.iflix.com]
55  UDP 192.168.1.1:53 <-> 192.168.1.105:46080 [proto: 5.216/DNS.IFLIX][1 pkts/85 bytes][Host: feature-service.iflix.com]
78  UDP 192.168.1.1:53 <-> 192.168.1.105:34406 [proto: 5/DNS][1 pkts/77 bytes][Host: app.iflixcorp.com]
79  UDP 192.168.1.1:53 <-> 192.168.1.105:46650 [proto: 5/DNS][1 pkts/77 bytes][Host: app.iflixcorp.com]
80  UDP 192.168.1.1:53 <-> 192.168.1.105:47962 [proto: 5/DNS][1 pkts/77 bytes][Host: app.iflixcorp.com]
87  TCP 192.168.1.105:59148 <-> 54.254.157.233:443 [proto: 91.216/SSL.IFLIX][4 pkts/797 bytes][SSL client: feature-service.iflix.com]
88  TCP 192.168.1.105:59146 <-> 54.254.157.233:443 [proto: 91.216/SSL.IFLIX][4 pkts/797 bytes][SSL client: feature-service.iflix.com]
94  TCP 192.168.1.105:47798 <-> 54.251.182.168:443 [proto: 91/SSL][4 pkts/797 bytes][SSL client: app.iflixcorp.com]
96  TCP 192.168.1.105:59186 <-> 54.254.157.233:443 [proto: 91.216/SSL.IFLIX][4 pkts/797 bytes][SSL client: feature-service.iflix.com]
101 TCP 192.168.1.105:47844 <-> 54.251.182.168:443 [proto: 91/SSL][4 pkts/797 bytes][SSL client: app.iflixcorp.com]
109 UDP 192.168.1.1:53 <-> 192.168.1.105:17801 [proto: 5.216/DNS.IFLIX][1 pkts/75 bytes][Host: login.iflix.com]
110 UDP 192.168.1.1:53 <-> 192.168.1.105:51243 [proto: 5.216/DNS.IFLIX][1 pkts/75 bytes][Host: login.iflix.com]
111 UDP 192.168.1.1:53 <-> 192.168.1.105:29927 [proto: 5.216/DNS.IFLIX][1 pkts/75 bytes][Host: login.iflix.com]
112 TCP 52.77.94.65:443 <-> 192.168.1.105:56746 [proto: 91.216/SSL.IFLIX][4 pkts/483 bytes][SSL client: login.iflix.com]
124 TCP 52.77.94.65:443 <-> 192.168.1.105:56756 [proto: 91.216/SSL.IFLIX][4 pkts/483 bytes][SSL client: login.iflix.com]
130 TCP 52.77.94.65:443 <-> 192.168.1.105:56776 [proto: 91.216/SSL.IFLIX][4 pkts/483 bytes][SSL client: login.iflix.com]
```

^C

### CODE REVIEW

**Comment by mmanoj** [comment]
[iflixMerge.tar.gz](https://github.com/ntop/nDPI/files/548714/iflixMerge.tar.gz)

**Comment by kYroL01** [comment]
Added service by https://github.com/ntop/nDPI/commit/b8fb5fb403a48820787ea87bca63acbfd658d31c
Thank you

**Comment by mmanoj** [comment]
Thanks for the quick support, We will contribute more protocols and services in the future.

**Comment by mmanoj** [comment]
Pls update the ndpi home page also with iflix.

http://www.ntop.org/products/deep-packet-inspection/ndpi/

**Pull request closed without merging**
