### PR TITLE
Fix Grease values parsing in tls

### PR DESCRIPTION
**Pull request by havsah**
The check for grease was too broad and filtered some valid values.
In particular, the value 257 was skipped because it matched the previous check.
This has been discovered while parsing tests/pcap/443-firefox.pcap
expected ja3:
771,4865-4867-4866-49195-49199-52393-52392-49196-49200-49162-49161-49171-49172-51-57-47-53-10,0-23-65281-10-11-35-16-5-51-43-13-45-28-21,29-23-24-25-256-257,0
previously generated ja3:
771,4865-4867-4866-49195-49199-52393-52392-49196-49200-49162-49161-49171-49172-51-57-47-53-10,0-23-65281-10-11-35-16-5-51-43-13-45-28-21,29-23-24-25-256,0

Signed-off-by: Patrick Havelange <patrick.havelange_ext@softathome.com>

### CODE REVIEW

**Review by IvanNardi — APPROVED** [review]
Thanks for catching this error.
I double checked: these new values are equal to the ones calculated by Wireshark, so they should be right.

**Comment by aouinizied** [comment]
@IvanNardi Codiga is failing due to usual warnings (long function, etc). 
Current results were also cross checked with https://github.com/salesforce/ja3 results.
Can you please merge this PR in order to integrate this fix on a new release on nfstream side?

Thanks a lot,
Zied

**Comment by IvanNardi** [comment]
> Codiga is failing due to usual warnings (long function, etc).

@aouinizied, any chance you know any way to disable these warnings?

**Comment by IvanNardi** [comment]
@havsah: thanks for your contribution

**Pull request merged**
